Controllers/DegreeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAttendance.Data;
using WebAttendance.Models.ViewModels;

namespace WebAttendance.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DegreeController : Controller
    {
        private IDegreeRepository Repo { get; }

        private IAttendanceRepository _Repo { get; }
        public DegreeController(IDegreeRepository repo, IAttendanceRepository repository)
        {
            Repo = repo;
            _Repo = repository;
        }

        public IActionResult Index()
        {
            var degrees = Repo.GetAllAvailableDegrees();
            // ot nai noviq kum nai stariq ailqche 
            var result = degrees.OrderByDescending(x => x.Id);
            return View(result);
        }


        [HttpGet]
        public async Task<IActionResult> EditDegrees(int DegreesId)

        {
            var existingDegree = await Repo.GetDegrees(DegreesId);
            var viewModel = new DegreeViewModel { Degrees = existingDegree };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditDegrees(DegreeViewModel modifiedDegree)

        {
            if (ModelState.IsValid)
            {
                var existingDegree = modifiedDegree.Degrees;
                await Repo.EditDegrees(existingDegree);
            }
            return View(modifiedDegree);
        }


        [HttpPost]
        public async Task<IActionResult> DeleteDegree(int DegreesId)
        {
            var deleteMessage = await Repo.DeleteDegreesById(DegreesId);
            return Content(deleteMessage);
        }


        [HttpGet]

        public IActionResult CreateDegree()
        {
            var viewModel = new DegreeViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateDegree(DegreeViewModel degreeViewModel)
        {
            if (ModelState.IsValid)
            {
                await Repo.AddDegrees(degreeViewModel.Degrees);
                return RedirectToAction("CreateDegree");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult GetDegree(int id)
        {
            var deg = Repo.GetDegrees(id);

            if (deg != null)
            {
                return View(deg);
            }
            return NotFound();
        }

    }
}

Controllers/NonWorkingDaysController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAttendance.Data;
using WebAttendance.Models.ViewModels;

namespace WebAttendance.Controllers
{
    [Authorize(Roles = "Admin")]
    public class NonWorkingDaysController : Controller
    {
        private IProgramsRepository Repo { get; }

        private IAttendanceRepository _Repo { get; }

        private INWDRepository nWDRepo { get; }
        public NonWorkingDaysController(IProgramsRepository repo, IAttendanceRepository repository, INWDRepository nWDRepository)
        {
            Repo = repo;
            _Repo = repository;
            nWDRepo = nWDRepository;
        }
        public IActionResult Index()
        {
            var nonworkingdays = nWDRepo.GetAllAvailableNWD();
            return View(nonworkingdays);
        }

        [HttpGet]
        public async Task<IActionResult> EditNonWorkingDays(int NWDId)

        {
            var existingNWD = await nWDRepo.GetNWD(NWDId);
            var viewModel = new NonWorkingDaysViewModel { NonWorkingDays = existingNWD };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditNonWorkingDays(NonWorkingDaysViewModel nonWorkingDaysViewModel)

        {
            if (ModelState.IsValid)
            {
                var existingNWD = nonWorkingDaysViewModel.NonWorkingDays;
                await nWDRepo.EditNWD(existingNWD);
            }
            return View(nonWorkingDaysViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> DeleteNWD(int NWDId)
        {
            var deleteMessage = await nWDRepo.DeleteNWD(NWDId);
            return Content(deleteMessage);
        }


        [HttpGet]

        public IActionResult CreateNonWorkingDays()
        {
            var viewModel = new NonWorkingDaysViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateNonWorkingDays(NonWorkingDaysViewModel nonWorkingDaysViewModel)
        {
            if (ModelState.IsValid)
            {
                await nWDRepo.AddNWD(nonWorkingDaysViewModel.NonWorkingDays);
                return RedirectToAction("CreateNonWorkingDays");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult GetNWD(int id)
        {
            var dis = nWDRepo.GetNWD(id);

            if (dis != null)
            {
                return View(dis);
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult GetNWD()
        {
            var nonworkingdays = nWDRepo.GetAllAvailableNWD();
            return View(nonworkingdays);
        }

    }
}

Controllers/ProgramsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAttendance.Data;
using WebAttendance.Models;
using WebAttendance.Models.ViewModels;

namespace WebAttendance.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProgramsController : Controller
    {
        private IProgramsRepository Repo { get; }

        private IAttendanceRepository _Repo { get; }
        public ProgramsController(IProgramsRepository repo, IAttendanceRepository repository)
        {
            Repo = repo;
            _Repo = repository;
        }

        public List<Degrees> GetAllDegrees()
        {
            List<Degrees> degreesNames = _Repo.LetGetDegrees().ToList();
            return degreesNames;

        }
        public IActionResult Index(int DegreesId)
        {
            ViewBag.degreesNames = new SelectList(GetAllDegrees(), "Id", "Name");

            IEnumerable<Programs> programs;
            if (DegreesId > 0)
            {
                programs = Repo.GetProgramByDegreesId(DegreesId);
            }
            else
            {
                programs = Repo.GetAllAvailablePrograms();
            }

            return View(programs);
        }

        [HttpGet]
        public async Task<IActionResult> EditProgram(int ProgramsId)

        {
            ViewBag.degreesNames = new SelectList(GetAllDegrees(), "Id", "Name");
            var existingPrograms = await Repo.GetProgram(ProgramsId);
            var viewModel = new ProgramsViewModel { Programs = existingPrograms };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditProgram(ProgramsViewModel updatedProgram)

        {
            ViewBag.degreesNames = new SelectList(GetAllDegrees(), "Id", "Name");
            if (ModelState.IsValid)
            {
                var existingProgram = updatedProgram.Programs;
                await Repo.EditProgram(existingProgram);
            }
            return View(updatedProgram);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteProgram(int ProgramsId)
        {
            var deleteMessage = await Repo.DeleteProgramById(ProgramsId);
            return Content(deleteMessage);
        }

        [HttpGet]
        public IActionResult CreateProgram()
        {
            ViewBag.degreesNames = new SelectList(GetAllDegrees(), "Id", "Name");
            var viewModel = new ProgramsViewModel();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateProgram(ProgramsViewModel programsViewModel)
        {
            ViewBag.degreesNames = new SelectList(GetAllDegrees(), "Id", "Name");
            if (ModelState.IsValid)
            {
                await Repo.AddProgram(programsViewModel.Programs);
                return RedirectToAction("CreateProgram");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult GetProgram(int id)
        {
            var prog = Repo.GetProgram(id);

            if (prog != null)
            {
                return View(prog);
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult GetPrograms()
        {
            var programs = Repo.GetAllAvailablePrograms();
            return View(programs);
        }
    }
}

Controllers/SemesterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAttendance.Data;
using WebAttendance.Models.ViewModels;

namespace WebAttendance.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SemesterController : Controller
    {
        private ISemesterRepository Repo { get; }

        private IAttendanceRepository _Repo { get; }


        public SemesterController(ISemesterRepository repo, IAttendanceRepository repository)
        {
            Repo = repo;
            _Repo = repository;

        }
        public IActionResult Index()
        {
            var semesters = Repo.GetAllAvailableSemesters();
            var result = semesters.OrderByDescending(x => x.Id);
            return View(result);
        }


        [HttpGet]
        public async Task<IActionResult> EditSemester(int SemesterId)

        {
            var existingSemester = await Repo.GetSemester(SemesterId);
            var viewModel = new SemesterViewModel { Semester = existingSemester };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditSemester(SemesterViewModel modifiedSemester)

        {
            if (ModelState.IsValid)
            {
                var existingSemester = modifiedSemester.Semester;
                await Repo.EditSemester(existingSemester);
            }
            return View(modifiedSemester);
        }


        [HttpPost]
        public async Task<IActionResult> DeleteSemester(int SemesterId)
        {
            var deleteMessage = await Repo.DeleteSemesterById(SemesterId);
            return Content(deleteMessage);
        }


        [HttpGet]
        public IActionResult CreateSemester()
        {
            var viewModel = new SemesterViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateSemester(SemesterViewModel semesterViewModel)
        {
            if (ModelState.IsValid)
            {
                await Repo.AddSemester(semesterViewModel.Semester);
                return RedirectToAction("CreateSemester");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult GetSemester(int id)
        {
            var sem = Repo.GetSemester(id);

            if (sem != null)
            {
                return View(sem);
            }
            return NotFound();
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <script nomodule>window.MSInputMethodContext && document.documentMode && document.write('<link rel="stylesheet" href="/css/bootstrap-ie11.min.css"><script src="https://cdn.jsdelivr.net/combine/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js,npm/ie11-custom-properties@4,npm/element-qsa-scope@1"><\/script><script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=default%2CNumber.parseInt%2CNumber.parseFloat%2CArray.prototype.find%2CArray.prototype.includes"><\/script>');</script>
    <title>@ViewData["Title"] - WebAttendance</title>
    <link rel="stylesheet" href="~/bootstrapsuperhero1.css" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/black-tie/jquery-ui.css" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <header>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="sidebar-layout">
        <div class="sidebar-aside-content">
            <partial name="_MyPartialLayout" />        
        </div>

        <div class="container body-content sidebar-body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - All Rights Reserved</p>
            </footer>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MyPartialLayout.cshtml
@using Microsoft.AspNetCore.Identity
@using WebAttendance.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<div id="sidebar-wrapper">
    @if (User.IsInRole("Admin"))
    {

    <ul class="sidebar-nav">
        <li><a id="manage" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Профил </a></li>
        @{ var user = await UserManager.GetUserAsync(User);}
        <li><a asp-area="" asp-controller="Programs" asp-action="Index">Специалности</a></li>
        <li><a asp-area="" asp-controller="Semester" asp-action="Index">Семестри </a></li>
        <li><a asp-area="" asp-controller="NonWorkingDays" asp-action="Index">Неучебни дни</a></li>
        <li><a asp-area="" asp-controller="Degree" asp-action="Index">Образ. степени </a></li>
        <li><a asp-area="" asp-controller="UsersAlloewdToRegister" asp-action="Index">Рег. лица</a></li>
        <li> <a asp-action="Index" asp-controller="Home">Отраб.акад.часове</a></li>
        <li> <a asp-action="Index" asp-controller="Admin">Потребители</a></li>
        <li> <a asp-action="ListRoles" asp-controller="Administration">Роли</a></li>
    </ul>

    }

    else if (SignInManager.IsSignedIn(User))
    {
      
        var user = await UserManager.GetUserAsync(User);
        <ul class="sidebar-nav">
            <li><a id="manage" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Профил </a></li>
        </ul>
    }
</div>

@section Scripts {

    <script>
        function openSideNav() {
            var sideBarDisplay = document.getElementById("side-bar").style.width;
            if (sideBarDisplay == "150px") {
                document.getElementById("side-bar").style.width = "0px";
                document.getElementById("body-content").style.marginLeft = "0px";
            } else {
                document.getElementById("side-bar").style.width = "150px";
                document.getElementById("body-content").style.marginLeft = "150px";
            }
        }

    </script>
}