Controllers/UsersAlloewdToRegisterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAttendance.Data;
using WebAttendance.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAttendance.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAlloewdToRegisterController : Controller
    {

        private IAttendanceRepository _Repo { get; }

        private IAPtRRepository Repo { get; }
        public UsersAlloewdToRegisterController(IAPtRRepository repo, IAttendanceRepository repository)
        {
            Repo = repo;
            _Repo = repository;

        }
        public IActionResult Index()
        {
            var allowedNames = Repo.GetAllAvailableAPtoReg();
            return View(allowedNames);
        }

        [HttpGet]
        public async Task<IActionResult> EditAPtoReg(int APtoRegId)

        {
            var existingAPtoReg = await Repo.GetAPtoReg(APtoRegId);
            var viewModel = new AllowedPersonsToRegisterViewModel { AllowedPersonsToRegister = existingAPtoReg };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditAPtoReg(AllowedPersonsToRegisterViewModel allowedPersonsToRegisterView)

        {
            if (ModelState.IsValid)
            {
                var existingARtoReg = allowedPersonsToRegisterView.AllowedPersonsToRegister;
                await Repo.EditAPtoReg(existingARtoReg);
            }
            return View(allowedPersonsToRegisterView);
        }


        [HttpPost]
        public async Task<IActionResult> DeleteAPtoReg(int APtoRId)
        {
            var deleteMessage = await Repo.DeleteAPtoReg(APtoRId);
            return Content(deleteMessage);
        }


        [HttpGet]

        public IActionResult CreateAPtoReg()
        {
            var viewModel = new AllowedPersonsToRegisterViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAPtoReg(AllowedPersonsToRegisterViewModel allowedPersonsToRegisterViewModel)
        {
            if (ModelState.IsValid)
            {
                await Repo.AddAPtoReg(allowedPersonsToRegisterViewModel.AllowedPersonsToRegister);
                return RedirectToAction("CreateAPtoReg");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult GetAPtoReg(int id)
        {
            var person = Repo.GetAPtoReg(id);

            if (person != null)
            {
                return View(person);
            }
            return NotFound();
        }
    }
}

Views/UsersAlloewdToRegister/CreateAPtoReg.cshtml
@model WebAttendance.Models.ViewModels.AllowedPersonsToRegisterViewModel
<h1>Позволени за регистрация лица</h1>

<div asp-validation-summary="All">   </div>
<form method="post" asp-controller="UsersAlloewdToRegister" asp-action="CreateAPtoReg">
    <div class="border p-3">
        <div class="form-group row">
            <h2>Въведете три имена</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="@Model.AllowedPersonsToRegister.Name"></label>
                        <input asp-for="@Model.AllowedPersonsToRegister.Name" class="form-control" />
                    </div>
                    <p> </p>
                    <div class="form-group row">
                        <div class="col-2">
                            <input type="submit" class="btn btn-info w-75" value="Запис" />
                        </div>
                        <div class="col-2">
                            <a asp-action="Index" class="btn btn-danger w-75">Назад</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Views/UsersAlloewdToRegister/EditAPtoReg.cshtml
@model WebAttendance.Models.ViewModels.AllowedPersonsToRegisterViewModel

<h1>Три имена</h1>

<div asp-validation-summary="All">   </div>
<form method="post" asp-controller="UsersAlloewdToRegister" asp-action="EditAPtoReg">
    <input type="hidden" asp-for="@Model.AllowedPersonsToRegister.Id" />
    <div class="border p-3">
        <div class="form-group row">
            <h2>Моля редактирайте</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="@Model.AllowedPersonsToRegister.Name"></label>
                        <input asp-for="@Model.AllowedPersonsToRegister.Name" class="form-control" />
                    </div>
                    <p> </p>
                    <div class="form-group row">
                        <div class="col-2">
                            <input type="submit" class="btn btn-info w-75" value="Обнови" />
                        </div>
                        <div class="col-2">
                            <a asp-action="Index" class="btn btn-danger w-75">Назад</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Views/UsersAlloewdToRegister/Index.cshtml
@model IEnumerable<WebAttendance.Models.AllowedPersonsToRegister>

<h1>Позволени за регистрация лица</h1>

<div class=" container p-3">
    <div class="col-6">
        <div asp-validation-summary="All">   </div>
    </div>

    <div class="input-group">
        <div class="col-4 text-right">  <a asp-area="" asp-controller="UsersAlloewdToRegister" asp-action="CreateAPtoReg" class="btn btn-primary">Въведи ново лице</a> </div>
        <div class="form-outline">
            <input type="text" id="searchTextId" class="form-control" />
        </div>
        <button type="button" class="btn btn-primary">
            <i class="fa fa-search"></i>
        </button>
    </div>

    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">

            <thead>
                <tr>
                    <th>Три Имена</th>
                    <th>Редакция</th>
                    <th>Изтриване</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var allowedPerson in Model)
                {
                    <tr class="tableRows">
                        <td width="30%">@allowedPerson.Name</td>
                        <td><a class="btn btn-primary" asp-action="EditAPtoReg" asp-controller="UsersAlloewdToRegister" asp-route-APtoRegId="@allowedPerson.Id" role="button">Редакция</a></td>
                        <td><button class="btn btn-danger deletePerson" onclick="confirmAction()" value="@allowedPerson.Id" role="button">Изтриване</button></td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> Няма създадени записи </p>
    }



</div>


<!-- Modal -->
<div id="deleteMessageModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Server Message</h4>
            </div>
            <div class="modal-body">
                <p id="message"> </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>



@section Scripts {

    <script>

        function confirmAction() {
        }

        $(document).ready(function () {
            $(".deletePerson").on("click", function (e) {

                e.preventDefault();

                let confirmAction = confirm("Потвърджавате ли изтриването?");
                if (!confirmAction) {
                    alert("Изтриването отменено");
                    return
                }
                alert("Действието е извършено успешно");

                var personAllowedToRegId = $(this).val();

                $.ajax({

                    type: 'POST',
                    url: '/UsersAlloewdToRegister/DeleteAPtoReg',
                    data: { APtoRId: personAllowedToRegId },
                    success: function (data) {
                        $("#message").html(data);
                        $("#deleteMessageModal").modal("show");
                    }

                });

            });

            $("#deleteMessageModal").on("hidden.bs.modal", function () {
                location.reload();
            });

            $("#searchTextId").on("keyup", function () {
                var searchTextId = $(this).val();
                if (searchTextId != undefined && searchTextId != "") {
                    console.log(searchTextId);
                    $(".tableRows").hide();
                    $("td:contains(" + searchTextId + ")").parent().show();

                }
                else {
                    $(".tableRows").show();
                }
            });
        });

    </script>
}