Models/Attendance.cs
using WebAttendance.Data.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using WebAttendance.Areas.Identity.Data;

namespace WebAttendance.Models
{
    public class Attendance
    {
        public int Id { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Дата")]
        public DateTime Date { get; set; }

        [Display(Name = "Образователна степен")]
        public string Degree { get; set; }

        [Display(Name = "Форма на обучение")]
        public string Mode { get; set; }

        [Display(Name = "Курс")]
        public int Course { get; set; }

        [Display(Name = "Група")]
        public string Groupe { get; set; }

        [Display(Name = "Времеви диапазон")]
        public string Timeframe { get; set; }

        [Display(Name = "Вид занятие")]
        public string Type { get; set; }

        [Display(Name = "Часове")]
        public int Hours { get; set; }

        [Display(Name = "Зала")]
        public string Auditorium { get; set; }

        [Display(Name = "Забележка")]
        public string Note { get; set; }
        
        [Display(Name = "Специалност")]
        public string Programs { get; set; }

        [Display(Name = "Дисциплина")]
        public string Subjects { get; set; }
        public int ApplicationUserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

        [Display(Name = "Семестър")]
        public int SemesterId { get; set; }
        public Semester Semester { get; set; }

    }

}

Models/ViewModels/AttendanceViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;

namespace WebAttendance.Models.ViewModels
{
    public class AttendanceViewModel
    {

        public Attendance Attendance { get; set; }
         
        public int DegreeId { get; set; }

        public int DisciplineId { get; set; }

        public List<SelectListItem> AvailableTypes { get; set; } = new List<SelectListItem>()
        {
            new SelectListItem {Text="Семинарно упражнение"},
            new SelectListItem {Text="Лабораторно упражнение"},
            new SelectListItem {Text="Лекция"}

        };

        public List<SelectListItem> AvailableModes { get; set; } = new List<SelectListItem>()
        {
            new SelectListItem {Text="редовно" },
            new SelectListItem {Text="задочно" },
            

        };
    }
}

Controllers/AttendanceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAttendance.Areas.Identity.Data;
using WebAttendance.Data;
using WebAttendance.Models;
using WebAttendance.Models.ViewModels;

namespace WebAttendance.Controllers
{
    public class AttendanceController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private IAttendanceRepository Repo { get; }

        private readonly UserManager<ApplicationUser> _userManager;

        public AttendanceController(IAttendanceRepository repo, UserManager<ApplicationUser> userManager, IHttpContextAccessor httpContextAccessor)
        {
            _userManager = userManager;
            Repo = repo;
            this._httpContextAccessor = httpContextAccessor;
        }

        public List<Semester> GetAllSemesterDisplay()
        {
            List<Semester> semNames = Repo.GetAllSemesters().ToList();
            return semNames;
        }

        public JsonResult GetProgramsByProgramId(int DegreesId)
        {
            var programs = Repo.GetProgramsByDegreesId(DegreesId);
            return Json(new SelectList(programs, "Id", "Name"));
        }


        public List<Degrees> GetAllDegrees()
        {
            List<Degrees> degreeNames = Repo.LetGetDegrees().ToList();
            return degreeNames;

        }

        public List<Programs> GetAllPrograms()
        {
            List<Programs> programsNames = Repo.LetGetPrograms().ToList();
            return programsNames;

        }

        [Authorize]
        [HttpGet]
        public IActionResult GetAttendances()
        {
            var attend = Repo.GetAttendances();
            return View(attend);
        }

        [Authorize]
        [HttpGet]
        public IActionResult GetAttendance(int id)
        {
            var at = Repo.GetAttendance(id);

            if (at != null)
            {
                return View(at);
            }
            return NotFound();
        }


        [Authorize]
        [HttpGet]
        public IActionResult GetAttendanceById(int ApplicationUserId)
        {
            var at = Repo.GetAttendanceByUserId(ApplicationUserId);

            if (at != null)
            {
                return View(at);
            }
            return NotFound();
        }


        [Authorize]
        [HttpGet]
        public IActionResult CreateAttendance()
        {
            ViewBag.degreesNames = new SelectList(GetAllDegrees(), "Id", "Name");
            ViewBag.semNames = new SelectList(GetAllSemesterDisplay(), "Id", "Name");
            var viewModel = new AttendanceViewModel();
            return View(viewModel);
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateAttendance(AttendanceViewModel attendanceViewModel)
        {
                        
            ViewBag.degreesNames = new SelectList(GetAllDegrees(), "Id", "Name");
            ViewBag.semNames = new SelectList(GetAllSemesterDisplay(), "Id", "Name");
            attendanceViewModel.Attendance.Degree = GetAllDegrees().Where(x => x.Id == attendanceViewModel.DegreeId).Select(x => x.Name).FirstOrDefault();
 
            if (ModelState.IsValid)
            {

                Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
                var user = await GetCurrentUserAsync();
                var userId = user.Id;
                attendanceViewModel.Attendance.ApplicationUserId = userId;
                await Repo.AddAttendance(attendanceViewModel.Attendance);

                return RedirectToAction("LoggedUser");
            }
            return RedirectToAction("LoggedUser");
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeleteAttendance(int AttendanceId)

        {
            var deleteMessage = await Repo.DeleteAttendance(AttendanceId);
            return Content(deleteMessage);

        }


        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditAttendance(int AttendanceId)

        {
            var existingAttend = await Repo.GetAttendance(AttendanceId);


            List<Degrees> degrees = GetAllDegrees();
            ViewBag.degreesNames = new SelectList(degrees, "Id", "Name");
            ViewBag.semNames = new SelectList(GetAllSemesterDisplay(), "Id", "Name");


            var viewModel = new AttendanceViewModel { Attendance = existingAttend };
            viewModel.DegreeId = degrees.Where(d => d.Name == existingAttend.Degree).Select(d => d.Id).FirstOrDefault();
            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditAttendance(AttendanceViewModel modifiedAttendance)

        {
            ViewBag.degreesNames = new SelectList(GetAllDegrees(), "Id", "Name");
            ViewBag.semNames = new SelectList(GetAllSemesterDisplay(), "Id", "Name");



            modifiedAttendance.Attendance.Degree = GetAllDegrees().Where(x => x.Id == modifiedAttendance.DegreeId).Select(x => x.Name).FirstOrDefault();
            if (ModelState.IsValid)
            {
                var existingAttend = modifiedAttendance.Attendance;
                await Repo.EditAttendance(existingAttend);
            }
            return View(modifiedAttendance);
        }


        [Authorize]
        public async Task<IActionResult> CoppyAttendance(int AttendanceId)

        {
            var existingAttend = await Repo.GetAttendance(AttendanceId);
            Repo.Detached(existingAttend);
            await Repo.AddAttendance(existingAttend);
            return RedirectToAction("LoggedUser");
        }

        [Authorize]
        public async Task<IActionResult> LoggedUser(string mode)
        {


            TempData.Keep();
            List<SelectListItem> times = new List<SelectListItem>()
                    {
                                new SelectListItem {
                                    Text = "1", Value = "1"
                                },
                                new SelectListItem {
                                    Text = "2", Value = "2"
                                },
                                new SelectListItem {
                                    Text = "3", Value = "3"
                                },
                                new SelectListItem {
                                    Text = "4", Value = "4"
                                },
                                new SelectListItem {
                                    Text = "5", Value = "5"
                                },

                     };
            ViewBag.Times = times;

            Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
            var user = await GetCurrentUserAsync();
            var userId = user.Id;
            IEnumerable<Attendance> attendances;

            var currentSelectedSemester = int.Parse(_httpContextAccessor.HttpContext.Request.Cookies["SemesterId"]);

            if (currentSelectedSemester != null)
            {
                attendances = Repo.FindAttendanceBySemesterIdandUserId(userId, currentSelectedSemester, mode);
            }
            else
            {
                attendances = Repo.FindAttendanceByUserId(userId, mode);
            }

            var result = attendances.OrderBy(x => x.Date);

            return View(result);
        }

        [Authorize]
        public async Task<IActionResult> MultiplicationByAttendanceId(int AttendanceId, int MultiplicationLength)
        {

            var length = MultiplicationLength;
            var attendance = await Repo.GetAttendance(AttendanceId);
            var semester = Repo.SemesterEndDateById(attendance.SemesterId);


            for (int i = 0; i < length; i++)
            {
                var newAttendanceDate = attendance.Date.AddDays(0);
                if (newAttendanceDate < semester)
                {
                    Repo.Detached(attendance);
                    attendance.Date = newAttendanceDate;
                    //await Repo.AddAttendanceWithoutHolidays(attendance);
                    await Repo.AddAttendance(attendance);

                }
            }
            return RedirectToAction("LoggedUser");
        }

        [Authorize]
        public async Task<IEnumerable<Attendance>> AttendanceByUserId()
        {
            Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
            var user = await GetCurrentUserAsync();
            var userId = user.Id;
            IEnumerable<Attendance> attendances = Repo.FindAttendanceByUserId(userId);
            var result = attendances.OrderBy(x => x.Date);
            return result;
        }

        [Authorize]
        public async Task<IActionResult> Multiplication(string mode = "редовно")
        {
            Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
            var user = await GetCurrentUserAsync();
            var userId = user.Id;
            var currentSelectedSemester = int.Parse(_httpContextAccessor.HttpContext.Request.Cookies["SemesterId"]);
            IEnumerable<Attendance> attendances;

            if (currentSelectedSemester != null)
            {
                attendances = Repo.FindAttendanceBySemesterIdandUserId(userId, currentSelectedSemester, mode).ToList();
            }
            else
            {
                attendances = Repo.FindAttendanceByUserId(userId, mode).ToList();
            }

            foreach (var attendance in attendances)
            {
                var semesterEndDate = Repo.SemesterEndDateById(attendance.SemesterId);

Views/Attendance/CreateAttendance.cshtml
@model WebAttendance.Models.ViewModels.AttendanceViewModel

<h1>Отработени академични часове </h1>

<div asp-validation-summary="All">   </div>
<form method="post" asp-controller="Attendance" asp-action="CreateAttendance">
    <div class="border p-3">
        <div class="form-group row">
            <h2>Въведете</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Date"></label>
                        <input id="datepicker1" asp-for="@Model.Attendance.Date" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Degree"></label>
                        <select id="DegreesList" class="form-control" asp-for="@Model.DegreeId" asp-items="@ViewBag.degreesNames">
                            <option selected disabled>---Изберете----</option>
                        </select>
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Mode"></label>
                        <select asp-for="@Model.Attendance.Mode" asp-items="@Model.AvailableModes" class="form-control">
                            <option selected disabled> ---Изберете----</option>
                        </select>
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Course"></label>
                        <input type="number" min="0" asp-for="@Model.Attendance.Course" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Groupe"></label>
                        <input asp-for="@Model.Attendance.Groupe" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Timeframe"></label>
                        <input asp-for="@Model.Attendance.Timeframe" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Type"></label>
                        <select asp-for="@Model.Attendance.Type" asp-items="@Model.AvailableTypes" class="form-control">
                            <option selected disabled> ---Изберете----</option>
                        </select>
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Hours"></label>
                        <input type="number" min="0" asp-for="@Model.Attendance.Hours" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Auditorium"></label>
                        <input asp-for="@Model.Attendance.Auditorium" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Note"></label>
                        <input asp-for="@Model.Attendance.Note" autocomplete="off" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Subjects"></label>
                        <input asp-for="@Model.Attendance.Subjects" autocomplete="off" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Programs"></label>
                        <select id="DisciplineList" asp-for="@Model.Attendance.Programs" class="form-control">
                            <option value="-1"> Изберете специалност</option>
                        </select>
                    </div>
                    <div class="col-3" style="display:none;">
                        <label asp-for="@Model.Attendance.ApplicationUserId" style-display="none" visible="false"></label>
                    </div>

                    <div class="col-3" style="display:none;">
                        <label asp-for="@Model.Attendance.SemesterId" visible="false"> </label>
                        <input asp-for="@Model.Attendance.SemesterId" class="form-control" />
                    </div>
                </div>
                <p> </p>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Запис" />
                        </div>
                        <div class="col">
                            <a asp-action="LoggedUser" class="btn btn-danger w-75">Назад</a>
                        </div>
                    </div>
                </div>
                <div style="display:none;">
                    <label asp-for="@Model.Attendance.ApplicationUserId" visible="false"> </label>
                </div>
            </div>
        </div>
    </div>
</form>

<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" rel="stylesheet" />
@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js">    </script>


    <script>
        $(document).ready(function () {
            $("#DegreesList").change(function () {
                $("#DisciplineList").empty();
                debugger
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("GetProgramsByProgramId")",
                    dataType: "json",
                    data: { DegreesId: $("#DegreesList").val() },
                    success: function (disciplines) {
                        $("#DisciplineList").append('<option value"' + -1 + ' " >' + "Изберете специалност" + '</option>');
                        $.each(disciplines, function (index , discipline) {
                            $("#DisciplineList").append('<option value"' + discipline.value + ' " >' + discipline.text + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed to retreive states ' + ex);
                    }
                })
                return false;
            })
        })

        var cookie_val = $.cookie("SemesterId");
        $('input[id=Attendance_SemesterId]').val(cookie_val);

        $('input[type="datetime-local"]').attr('type', 'text');

        $(function () {
            $("#datepicker1").datepicker();
        });
    </script>

}

Views/Attendance/EditAttendance.cshtml
@model WebAttendance.Models.ViewModels.AttendanceViewModel

<div asp-validation-summary="All">   </div>
<form method="post" asp-controller="Attendance" asp-action="EditAttendance">
    <input type="hidden" asp-for="@Model.Attendance.Id" />
    <div class="form-group row">
        <h2>Моля редактирайте</h2>
    </div>
    <div class="border p-3">
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Date"></label>
                        <input id="datepicker2" asp-for="@Model.Attendance.Date" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Degree"></label>
                        <select id="DegreesList" class="form-control" asp-for="@Model.DegreeId" asp-items="@ViewBag.degreesNames">
                            <option selected disabled>---Изберете----</option>
                        </select>
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Mode"></label>
                        <select asp-for="@Model.Attendance.Mode" asp-items="@Model.AvailableModes" class="form-control">
                            <option selected disabled> ---Изберете----</option>
                        </select>
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Course"></label>
                        <input type="number" min="0" asp-for="@Model.Attendance.Course" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Groupe"></label>
                        <input asp-for="@Model.Attendance.Groupe" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Timeframe"></label>
                        <input asp-for="@Model.Attendance.Timeframe" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Type"></label>
                        <select asp-for="@Model.Attendance.Type" asp-items="@Model.AvailableTypes" class="form-control">
                            <option selected disabled> ---Изберете----</option>
                        </select>
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Hours"></label>
                        <input type="number" min="0" asp-for="@Model.Attendance.Hours" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Auditorium"></label>
                        <input asp-for="@Model.Attendance.Auditorium" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Note"></label>
                        <input asp-for="@Model.Attendance.Note" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Subjects"></label>
                        <input asp-for="@Model.Attendance.Subjects" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="@Model.Attendance.Programs"></label>
                        <select id="DisciplineList" asp-for="@Model.Attendance.Programs" class="form-control">
                            <option value="-1"> Изберете специалност</option>
                        </select>
                    </div>
                    <div class="col-3" style="display:none;">
                        <label asp-for="@Model.Attendance.ApplicationUserId" style-display="none" visible="false"></label>
                    </div>

                    <div class="col-3" style="display:none;">
                        <label asp-for="@Model.Attendance.SemesterId" visible="false"> </label>
                        <input asp-for="@Model.Attendance.SemesterId" class="form-control" />
                    </div>
                </div>
                <p> </p>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Обнови" />
                        </div>
                        <div class="col">
                            <a asp-action="LoggedUser" class="btn btn-danger w-75">Назад</a>
                        </div>
                    </div>
                </div>
                <div style="display:none;">
                    <label asp-for="@Model.Attendance.ApplicationUserId" visible="false"> </label>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script>

        $(document).ready(function () {
            $("#DegreesList").change(function () {
                $("#DisciplineList").empty();

                debugger
                $.ajax({
                    type: "GET",

                    url: "@Url.Action("GetProgramsByProgramId")",
                    dataType: "json",
                    data: { DegreesId: $("#DegreesList").val() },
                    success: function (disciplines) {
                        $("#DisciplineList").append('<option value"' + -1 + ' " >' + "Изберете специалност" + '</option>');
                        $.each(disciplines, function (index , discipline) {
                            $("#DisciplineList").append('<option value"' + discipline.value + ' " >' + discipline.text + '</option>');
                        });

                    },
                    error: function (ex) {
                        alert('Failed to retreive states ' + ex);
                    }
                })
                return false;
            })
        })

        $('input[type="datetime-local"]').attr('type', 'text');

        $(function () {
            $("#datepicker2").datepicker();
        });
    </script>

}

Views/Attendance/Index.cshtml
@model IEnumerable<WebAttendance.Models.Semester>
@using Microsoft.AspNetCore.Identity
@using WebAttendance.Data.Models
@using WebAttendance.Areas.Identity.Data


@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<div class="panel panel-body">
    <div class="col-md-6">

        @if (SignInManager.IsSignedIn(User))
        {
            var user = await UserManager.GetUserAsync(User);

            <h1>Здравейте @user.OfficialName</h1>
            <a class="btn btn-primary" asp-action="LoggedUser" asp-controller="Attendance" role="button">Попълнете присъствената форма</a>

        }

        else
        {
            <h1>А СЯ ДЕ</h1>
        }
    </div>
</div>


@*onchange="javascript:this.form.submit()"*@

Views/Attendance/UserHistory.cshtml
@{
    Layout = null;
}

@model IEnumerable<WebAttendance.Models.Attendance>
@using Microsoft.AspNetCore.Identity
@using WebAttendance.Data.Models
@using WebAttendance.Areas.Identity.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager



<style>

    .btn {
        display: inline-block;
        color: #444;
        border: 1px solid #CCC;
        background: #DDD;
        box-shadow: 0 0 5px -1px rgba(0,0,0,0.2);
        cursor: pointer;
        vertical-align: middle;
        max-width: 100px;
        padding: 5px;
        text-align: center;
    }

    table {
        font-family: Arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    @@media print {
        #printPageButton {
            display: none;
        }
    }

    @@media print {
        #printPageButton1 {
            display: none;
        }
    }

    @@media print {
        #printPageButton2 {
            display: none;
        }
    }
</style>



<div class=" container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <div asp-validation-summary="All"> </div>
        </div>
    </div>

    <br />

    @{ var user = await UserManager.GetUserAsync(User);}

    <h1>@user.Description @user.OfficialName</h1>

    <br />
    <p> <div>@TempData["semesterName"]</div></p>

    @if (Model.Count() > 0)
    {
        <table>

            <thead>
                <tr>
                    <th>Дата</th>
                    <th>Степен</th>
                    <th>Вид</th>
                    <th>Курс</th>
                    <th>Група</th>
                    <th>Час.Диапазон</th>
                    <th>Тип</th>
                    <th>Часове</th>
                    <th>Зала</th>
                    <th>Забележка</th>
                    <th>Предмет</th>
                    <th>Специалност</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var attendance in Model)
                {
                    <tr class="tableRows">
                        <td width="8%">@attendance.Date</td>
                        <td width="8%">@attendance.Degree</td>
                        <td width="8%">@attendance.Mode</td>
                        <td width="4%">@attendance.Course</td>
                        <td width="4%">@attendance.Groupe</td>
                        <td width="8%">@attendance.Timeframe</td>
                        <td width="8%">@attendance.Type</td>
                        <td width="4%">@attendance.Hours</td>
                        <td width="8%">@attendance.Auditorium</td>
                        <td width="8%">@attendance.Note</td>
                        <td width="8%">@attendance.Subjects</td>
                        <td width="12%">@attendance.Programs</td>
                    </tr>
                }
            </tbody>
        </table>

    }
    else
    {
        <p> </p>
    }
    <form>
        <input class='btn' id="printPageButton" type="button" value="Принтиране"
               onclick="window.print()" />
    </form>

    <div class='btn' id="printPageButton2"><a type="button" a asp-controller="Attendance" asp-action="LoggedUser">Назад </a></div>
    <div >Подпис : </div>
</div>